const palette = {
  redPrimary: "#C40F20",
  redPrimaryLight: "#E38D93",
  tealPrimary: "#048086",
  greenPrimary: "#074C4E",
  greenPrimaryLight: "#EAF6F6",
  carrotSecondary: "#F86F2D",
  carrotSecondaryLight: "#FAE6DD",
  greenSuccess: "#4ABC86",
  greenSuccessLight: "#D8FFEC",
  redError: "#EA3838",
  redErrorLight: "#FBECEC",
  core: "#66376D",
  coreLight: "#c1afc4",
  purple: "#992599",
  grayBlack: "#000000",
  gray1: "#636363",
  gray2: "#8E8E8E",
  gray3: "#B3B3B3",
  gray4: "#E1E1E1",
  gray5: "#F5F5F5",
  grayWhite: "#FFFFFF",
  white: "#FFFFFF",
  background_light: "#f6f6f6",
  shape_light: "#ffffff",
  text_light: "#262626",
  background_dark: "#121212",
  shape_dark: "#202020",
  text_dark: "#e2dce2",
  yellowPrimary: "#F6D02F",
  orangePrimary: "#ffa500",
  transparent: "transparent",
  gradientStart: "#cf5149",
  gradientEnd: "#9d2e82",
};

/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./hooks/**/*.{js,jsx,ts,tsx}",
    "./services/**/*.{js,jsx,ts,tsx}",
    "./*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        redPrimary: palette.redPrimary,
        redPrimaryLight: palette.redPrimaryLight,
        tealPrimary: palette.tealPrimary,
        greenPrimary: palette.greenPrimary,
        greenPrimaryLight: palette.greenPrimaryLight,
        carrotSecondary: palette.carrotSecondary,
        carrotSecondaryLight: palette.carrotSecondaryLight,
        greenSuccess: palette.greenSuccess,
        greenSuccessLight: palette.greenSuccessLight,
        redError: palette.redError,
        redErrorLight: palette.redErrorLight,
        core: palette.core,
        coreLight: palette.coreLight,
        purple: palette.purple,
        grayBlack: palette.grayBlack,
        gray1: palette.gray1,
        gray2: palette.gray2,
        gray3: palette.gray3,
        gray4: palette.gray4,
        gray5: palette.gray5,
        grayWhite: palette.grayWhite,
        white: palette.white,
        background_light: palette.background_light,
        shape_light: palette.shape_light,
        text_light: palette.text_light,
        background_dark: palette.background_dark,
        shape_dark: palette.shape_dark,
        text_dark: palette.text_dark,
        yellowPrimary: palette.yellowPrimary,
        orangePrimary: palette,
        transparent: palette.transparent,
        gradientStart: palette.gradientStart,
        gradientEnd: palette.gradientEnd,
      },
      fontFamily: {
        regular: ["SpaceMono-Regular"],
      },
    },
  },
  plugins: [],
};
